# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_merge'),
        ('fitapp', '0008_remove_userfitbit_auth_secret'),
    ]

    operations = [
    ]
