# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-18 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    UserModel = getattr(settings, 'FITAPP_USER_MODEL', 'auth.User')

    dependencies = [
        ('fitapp', '0011_userfitbit_uuid'),
        migrations.swappable_dependency(UserModel),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepStageTimeSeriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='The date the data was recorded')),
                ('level', models.CharField(help_text='Sleep stages', max_length=32)),
                ('seconds', models.IntegerField(help_text='The amount of time last for this sleep period')),
                ('user', models.ForeignKey(help_text="The data's user",
                                           on_delete=django.db.models.deletion.CASCADE, to=UserModel)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sleepstagetimeseriesdata',
            unique_together=set([('user', 'date')]),
        ),
    ]
