# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-25 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    UserModel = getattr(settings, 'FITAPP_USER_MODEL', 'auth.User')

    dependencies = [
        ('fitapp', '0012_add_sleep_stage_time_series_data'),
        migrations.swappable_dependency(UserModel),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepStageSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='The date the data was recorded')),
                ('user', models.ForeignKey(help_text="The data's user",
                                           on_delete=django.db.models.deletion.CASCADE, to=UserModel)),
            ],
        ),
        migrations.CreateModel(
            name='SleepTypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Sleep stages', max_length=32)),
                ('count', models.IntegerField(help_text='Number of this type of sleep status')),
                ('minute', models.IntegerField(help_text='How long this type of sleep last in total')),
                ('sleep_summary', models.ForeignKey(help_text='The summary object that this sleep associated with', on_delete=django.db.models.deletion.CASCADE, to='fitapp.SleepStageSummary')),
            ],
        ),
        migrations.AlterField(
            model_name='sleepstagetimeseriesdata',
            name='date',
            field=models.DateTimeField(help_text='The date and time the data was recorded'),
        ),
    ]
