# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-25 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0013_auto_20180425_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepstagesummary',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='sleeptypedata',
            unique_together=set([('sleep_summary', 'level')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='sleeptypedata',
            order_with_respect_to='sleep_summary',
        ),
    ]
