# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-25 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0014_auto_20180425_1448'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='sleeptypedata',
            order_with_respect_to=None,
        ),
    ]
