# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0015_auto_20180425_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleeptypedata',
            options={'ordering': ['sleep_summary']},
        ),
        migrations.AlterUniqueTogether(
            name='sleepstagesummary',
            unique_together=set([('user', 'date')]),
        ),
    ]
